# Introduction to Numpy
---

**Objective:**

In this exercise, you will be covering the basics of a  very useful library in Python called Numpy. Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

Source found [here](http://cs231n.github.io/python-numpy-tutorial/).


In [ ]:
#import the Numpy library
import numpy as np

## Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
# Create a rank 1 array with the following elements: 1,2,1,3
a = _____

#print type
print(type(a))  

# print the shape          
print(_____)

# print the first 3 values
print(_____)

In [ ]:
# Change the first element of the array to 5
_______
print(a)                 

In [ ]:
# Create a rank 2 array: 2 arrays with 3 elements each
b = _______ 

print(b.shape)    

#print elements 1, 2 and 4 in the above array
print(________)  

Numpy also provides many functions to create arrays:

In [ ]:
# Create a 2x2 array of zeros
a = _____
print(a)            

In [ ]:
# Create a 2x3 array of ones
b = _______   
print(b)

## Array Indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = __________
print(a, a.shape)

In [ ]:
# Use slicing to pull out a subarray b consisting of the first 2 rows
# and columns 1 and 2; b is the array of shape (2, 2) will consist of:
# [[2 3]
#  [6 7]]
b = ______
print(b, b.shape)

In [ ]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.

# b[0, 0] is the same piece of data as a[0, 1]
b[0, 0] = 77
print(a[0, 1])
print(a)

One useful trick with for creating integer arrays is using `arange()` to create an array from numerical ranges:

In [ ]:
#Create an array of numbers from 0 to 4 (exclusive) using arange()
np.arange(4)

In [ ]:
#Create an array of numbers from 0 to 12 (exclusive) with a separation step of 3 using arange()
np._______

## Array Math
<b>Elementwise</b> array operations execute element by element operations on corresponding elements of arrays

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Do an Elementwise SUM of x and y using +
print(x + y)

In [ ]:
#Do the same elementwise SUM but use a method to do so:
print(np.add(x, y))

In [ ]:
#Do an Elementwise PRODUCT of x and y
print(x * y)

In [ ]:
# #Do the same elementwise PRODUCT but use a method to do so:
print(np.multiply(x, y))

<b>Matrix multiplication</b>: use the dot() function to compute inner products of arrays of the same size.<br/> Reminder: "*" is elementwise multiplication, not matrix multiplication.

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# dot product of x and y
print(x.dot(y))
# OR
print(np.dot(x,y))

## Changing Array Dimensions

In [ ]:
#Create an array a of numbers 0 to 5 (inclusive)
a = _______
a

In [ ]:
#Reshape a to an array b of dimentions 3x2
#print the array before then after reshaping
b = _______

print('Before reshaping:\n', a)
print('\nAfter reshaping:\n', b)

In [ ]:
#Reshape b to one array c (of 6 elements)
c = ______
print(c)

In [ ]:
#Create an array of numbers from 1 to 15 (inclusive) and reshape in 3 arrays with 5 elements
a = ______
print(a)